_wandb:
    value:
        cli_version: 0.25.0
        e:
            49n9i0l5jah60y134x5ubjnt4waazgdc:
                args:
                    - --model_path
                    - src/best_model.npy
                    - --dataset
                    - mnist
                    - --batch_size
                    - "64"
                    - --num_hidden_layers
                    - "3"
                    - --hidden_size
                    - "128"
                    - --activation
                    - relu
                codePath: src\inference.py
                codePathLocal: src\inference.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "11.1"
                disk:
                    /:
                        total: "911430643712"
                        used: "392521011200"
                email: id25s004@smail.iitm.ac.in
                executable: C:\Users\bsvp\AppData\Local\Programs\Python\Python314\python.exe
                gpu: GeForce GT 710
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Kepler
                      name: GeForce GT 710
                      uuid: GPU-51a63ef1-f31f-4edd-991a-991b42ca403e
                host: DESKTOP
                memory:
                    total: "34113650688"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\bsvp\Downloads\da6401_assignment_1-main\da6401_assignment_1-main\da6401_assignment_1-main\src\inference.py
                python: CPython 3.14.3
                root: C:\Users\bsvp\Downloads\da6401_assignment_1-main\da6401_assignment_1-main\da6401_assignment_1-main
                startedAt: "2026-03-07T17:29:44.004737Z"
                writerId: 49n9i0l5jah60y134x5ubjnt4waazgdc
        m: []
        python_version: 3.14.3
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.14.3
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
