wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 64
learning_rate:
  value: 0.0015
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: sgd
weight_decay:
  value: 0.001
weight_init:
  value: xavier
