wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 128
learning_rate:
  value: 0.002
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: xavier
